//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal_Ecommerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesBolsas1 : DbContext
    {
        public EntitiesBolsas1()
            : base("name=EntitiesBolsas1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PagoProveedores> PagoProveedores { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<SolicitudesCompras> SolicitudesCompras { get; set; }
        public virtual DbSet<SolicitudesDevoluciones> SolicitudesDevoluciones { get; set; }
        public virtual DbSet<SolicitudesOfertas> SolicitudesOfertas { get; set; }
        public virtual DbSet<SolicitudesVentasActualizar> SolicitudesVentasActualizar { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
