//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal_Ecommerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesPreciosNuevos : DbContext
    {
        public EntitiesPreciosNuevos()
            : base("name=EntitiesPreciosNuevos")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CambioPrecioVenta> CambioPrecioVenta { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<SolicitudesCambioPrecio> SolicitudesCambioPrecio { get; set; }
    }
}
