//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudesCambioPrecio
    {
        public int Id { get; set; }
        public Nullable<int> Id_Producto { get; set; }
        public Nullable<double> PrecioActual { get; set; }
        public Nullable<int> Id_TipoCambio { get; set; }
        public Nullable<double> NuevoPrecio { get; set; }
        public Nullable<double> Descuento { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual CambioPrecioVenta CambioPrecioVenta { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
